# Using latest node version
image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
   - test
   - staging
   - production

variables:
  CLI_VERSION: 11.2.7

test:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  script:
  - ng test
  tags:
  - docker

staging:
   type: deploy
   stage: staging
   image: ruby:latest
   script:
     - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
   only: 
     - staging

production:
   type: deploy
   stage: production
   image: ruby:latest 
   script:
     - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY

   only:
    - master 

  


