# Using latest node version
image: node:latest

stages:
   - staging
   - production

staging:
   type: deploy
   stage: staging
   image: ruby:latest
   script:
     - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
   only: 
     - staging

production:
   type: deploy
   stage: production
   image: ruby:latest 
   script:
     - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY

   only:
    - master 

  


